In [1]:
import numpy as np
import pandas as pd
from imblearn.over_sampling import SMOTE
from collections import Counter
from nltk.corpus import stopwords

In [2]:
df=pd.read_csv(r'C:\Users\ADMIN\Desktop\innox\train_F3WbcTw.csv')
df1=pd.read_csv(r'C:\Users\ADMIN\Desktop\innox\test_tOlRoBf.csv')

In [3]:
stop = stopwords.words('english')


In [4]:
df['text'] = df['text'].apply(lambda x: ([x for x in x.split() if x.lower() not in stop]))
df1['text'] = df1['text'].apply(lambda x: ([x for x in x.split() if x.lower() not in stop]))

In [5]:
df['text'] = df['text'].apply(lambda x: ([y for y in x if  len(y)>2 ]))
df1['text'] = df1['text'].apply(lambda x: ([y for y in x if len(y)>2 ]))

In [6]:
import string 

In [7]:
sp_w=string.punctuation

In [8]:
df['text']=df['text'].apply(lambda x: ' '.join([each for each in x if each not in sp_w]))
df1['text']=df1['text'].apply(lambda x: ' '.join([each for each in x if each not in sp_w]))    

In [15]:
df['text'] = df['text'].str.replace('[^\w\s]','')
df1['text'] = df1['text'].str.replace('[^\w\s]','')

In [16]:
df['text']

0       Autoimmune diseases tend come clusters Gilenya...
1       completely understand youd want try it But res...
2       Interesting targets SP receptors rather  like ...
3       interesting grand merci wonder lemtrada ocrevu...
4       everybody latest MRI results Brain Cervical Co...
5       cant give advice Lemtrada chose Cladribine tho...
6       Reply posted JessZidek Jess Sorry read challen...
7       Well expected Neurologist wants start Tysabri ...
8       think FIngolimod miserable failure progressive...
9       Thank muchIm learning lot GRACE mentioned husb...
10      vision one eye unrelated eye injections Howeve...
11      significant bleeding right eye need laser poss...
12      Objective review evidence supporting European ...
13      Multiple sclerosis MS thought inflammatory pro...
14      Moms diagnosis similar own Mine detected Janua...
15      Humira adalimumab injectable protein antibody ...
16      Well theory telling accurate standard practice...
17      goodne

In [17]:
df1['text']=df1['text'].apply(lambda x: [i for i in x.split() if not str(i).isdigit()])
df['text']=df['text'].apply(lambda x: [i for i in x.split() if not str(i).isdigit()])

In [18]:
df1['text']

0       [previously, stable, natalizumab, switching, f...
1       [fingolimod, since, December, way, describe, b...
2       [Apparently, shingles, red, spots, left, breas...
3       [Docetaxel, week, weeks, week, claim, less, ha...
4       [CC, Stelara, worked, matter, days, me, willin...
5       [Janssen, Biotech, Inc, received, FDA, approva...
6       [the, thought, things, would, better, now, one...
7       [Dec, Basha, Fowler, diagnosed, rd, week, Dec,...
8       [Hi, started, Gilenya, weeks, ago, woeful, anx...
9       [uncle, still, going, treatment, kinds, Chemo,...
10      [daughter, Stage, adenocarcinoma, NSCLC, ROS, ...
11      [nt, Toxicity, would, probably, main, objectio...
12      [Thanks, Jim, Thanks, Janine, Kidney, failure,...
13      [Hey, iPoop, tried, clicking, link, work, went...
14      [Bad, lifetime, nearsightedness, os, led, macu...
15      [Janine, ever, heard, KRAS, mutation, mutating...
16      [The, important, metric, brain, volume, loss, ...
17      [Hello

In [36]:
import re


In [19]:
df['text']

0       [Autoimmune, diseases, tend, come, clusters, G...
1       [completely, understand, youd, want, try, it, ...
2       [Interesting, targets, SP, receptors, rather, ...
3       [interesting, grand, merci, wonder, lemtrada, ...
4       [everybody, latest, MRI, results, Brain, Cervi...
5       [cant, give, advice, Lemtrada, chose, Cladribi...
6       [Reply, posted, JessZidek, Jess, Sorry, read, ...
7       [Well, expected, Neurologist, wants, start, Ty...
8       [think, FIngolimod, miserable, failure, progre...
9       [Thank, muchIm, learning, lot, GRACE, mentione...
10      [vision, one, eye, unrelated, eye, injections,...
11      [significant, bleeding, right, eye, need, lase...
12      [Objective, review, evidence, supporting, Euro...
13      [Multiple, sclerosis, MS, thought, inflammator...
14      [Moms, diagnosis, similar, own, Mine, detected...
15      [Humira, adalimumab, injectable, protein, anti...
16      [Well, theory, telling, accurate, standard, pr...
17      [goodn

In [20]:
d = {ord(x):"" for x in ":-()&*$%@!#|\{[]}/,' '.:; "}
df['text']=df['text'].apply(lambda orig_list : [x.translate(d) for x in orig_list])
df1['text']=df1['text'].apply(lambda orig_list : [x.translate(d) for x in orig_list])


In [33]:
df1['texts']=df1['text'].apply(lambda x: [i.lower() for i in x if len(str(i))>2])
df['texts']=df['text'].apply(lambda x: [i.lower() for i in x if len(str(i))>2])

In [35]:
df1['texts']

0       [previously, stable, natalizumab, switching, f...
1       [fingolimod, since, december, way, describe, b...
2       [apparently, shingles, red, spots, left, breas...
3       [docetaxel, week, weeks, week, claim, less, ha...
4       [stelara, worked, matter, days, willing, jump,...
5       [janssen, biotech, inc, received, fda, approva...
6       [the, thought, things, would, better, now, one...
7       [dec, basha, fowler, diagnosed, week, dec, egf...
8       [started, gilenya, weeks, ago, woeful, anxiety...
9       [uncle, still, going, treatment, kinds, chemo,...
10      [daughter, stage, adenocarcinoma, nsclc, ros, ...
11      [toxicity, would, probably, main, objection, c...
12      [thanks, jim, thanks, janine, kidney, failure,...
13      [hey, ipoop, tried, clicking, link, work, went...
14      [bad, lifetime, nearsightedness, led, macular,...
15      [janine, ever, heard, kras, mutation, mutating...
16      [the, important, metric, brain, volume, loss, ...
17      [hello

In [27]:
from textblob import Word

In [36]:
df['texts'] = df['texts'].apply(lambda x: [Word(word).lemmatize() for word in x])
df1['texts'] = df1['texts'].apply(lambda x: [Word(word).lemmatize() for word in x])

In [37]:
df['texts']

0       [autoimmune, disease, tend, come, cluster, gil...
1       [completely, understand, youd, want, try, but,...
2       [interesting, target, receptor, rather, like, ...
3       [interesting, grand, merci, wonder, lemtrada, ...
4       [everybody, latest, mri, result, brain, cervic...
5       [cant, give, advice, lemtrada, chose, cladribi...
6       [reply, posted, jesszidek, jess, sorry, read, ...
7       [well, expected, neurologist, want, start, tys...
8       [think, fingolimod, miserable, failure, progre...
9       [thank, muchim, learning, lot, grace, mentione...
10      [vision, one, eye, unrelated, eye, injection, ...
11      [significant, bleeding, right, eye, need, lase...
12      [objective, review, evidence, supporting, euro...
13      [multiple, sclerosis, thought, inflammatory, p...
14      [mom, diagnosis, similar, own, mine, detected,...
15      [humira, adalimumab, injectable, protein, anti...
16      [well, theory, telling, accurate, standard, pr...
17      [goodn

In [38]:
df2=pd.DataFrame()
df3=pd.DataFrame()
df4=pd.DataFrame()

In [39]:
df2['text']=df1['texts']
df3['text']=df['texts']

In [40]:
df4=df3.append(df2)

In [41]:
allwords=[]
for each in df4['text']:
    #print(each)
    
    #eachs =each.split(' ')

    allwords.extend(each)

In [42]:
dictionary=Counter(allwords)
list_of_word=dictionary.keys()
keyss=[]
for i in list_of_word:
    if i.isalpha()==False or len(i)<4:
        keyss.append(i)
    #if len(i)==1:
        #keyss.append(i)
#print(keyss)  
for i in keyss:
    dictionary.pop(i)
dictionary=dictionary.most_common(3000) 

In [43]:
features_test = np.zeros((2924,3000))
#train_labels=np.zeros(5279)
docID=0
for i in range(df1.shape[0]):
    #allwords=[]
    words=df1['texts'][i]
    #words = line.split(' ')
    allwords=[]
    allword=Counter(words)
    allwords+=allword.keys()
    for word in allwords:
        wordID = 0
        for j,d in enumerate(dictionary):
            if d[0] == word:
                wordID = j
                features_test[docID][wordID] = words.count(word)
    #train_labels[docID] = df['sentiment'][i]
    docID = docID + 1      

In [44]:
features_test = np.zeros((2924,3000))
#train_labels=np.zeros(5279)
docID=0
for i in range(df1.shape[0]):
    #allwords=[]
    words=df1['texts'][i]
    #words = line.split(' ')
    allwords=[]
    allword=Counter(words)
    allwords+=allword.keys()
    for word in allwords:
        wordID = 0
        for j,d in enumerate(dictionary):
            if d[0] == word:
                wordID = j
                features_test[docID][wordID] = words.count(word)
    #train_labels[docID] = df['sentiment'][i]
    docID = docID + 1 

In [45]:
method=SMOTE(kind='regular')
x_train,y_train=method.fit_sample(features_matrix,train_labels)

In [46]:
from sklearn.model_selection import train_test_split 
  

In [48]:
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 3).fit(x_train, y_train) 
dtree_predictions = dtree_model.predict(features_test) 
  

In [49]:
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
  

In [50]:
dtree_predictions

array([2., 2., 2., ..., 2., 2., 1.])

In [51]:
X_train, X_test, y_train, y_test = train_test_split(x_train, y_train, random_state = 0) 

In [52]:
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test)

In [53]:
accuracy = svm_model_linear.score(X_test, y_test) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 

In [55]:
print(accuracy)

0.8717323109097247


In [57]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV

In [71]:
def svc_param_selection(X, y,nfolds):
    Cs = [0.001, 0.01, 0.1, 1, 10]
    gammas = [0.001, 0.01, 0.1, 1]
    param_grid = {'C': Cs, 'gamma' : gammas}
    grid_search = GridSearchCV(svm.SVC(kernel='rbf'), param_grid,cv=nfolds)
    grid_search.fit(X, y)
    grid_search.best_params_
    return grid_search.best_params_

In [73]:
print(svc_param_selection(X_train,y_train,2))

{'C': 10, 'gamma': 0.01}


In [75]:
clf=svm.SVC(C=10,kernel='rbf',gamma=0.01)

In [76]:
clf.fit(X_train,y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [77]:
pred=clf.predict(X_test)
cm1 = confusion_matrix(y_test, pred)
print(cm1)


[[925   2  47]
 [  2 888  46]
 [ 82 105 772]]


In [ ]:
pry=clf.predict(features_test)
p1=pd.DataFrame()
p1['unique_hash']=df1['unique_hash']
p1['sentiment']=pry
p1.to_csv(r'C:\Users\ADMIN\Desktop\innox\sol4.csv',index=None)

In [ ]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0,solver='1bfgs',multi_class='multinomial').fit(X_train,y_train)